#!/bin/bash

cd /app/backend;

#echo "$nginx_ip  member-$MODE.yimei180.com"  >> /etc/hosts;

supervisor -w api,common,config,custom_components,middlewares,errors,nock,controllers,views,app.js app.js


