#!/bin/bash

cd /app/aegis-pay/backend;

#echo "$nginx_ip  member-$MODE.yimei180.com"  >> /etc/hosts;

supervisor -w api,config,controllers,custom_components,errors,middlewares,libs,routes,nock,app.js app.js


